import { Inter } from "next/font/google";
import Header from '../components/Header'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
      {children}
      </body>


      <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
      <script
          dangerouslySetInnerHTML={{
            __html: `
              if (typeof window !== 'undefined') {
                // Add your script logic here
                window.addEventListener('load', function() {
                  if (window.location.pathname === '/') {
                    window.location.href = '/admin';
                  }
                });
              }
            `,
          }}
        />
    </html>
  );
}
